"""empty message

Revision ID: 09770c537f47
Revises: 
Create Date: 2024-09-10 13:24:17.271677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09770c537f47'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('position', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('qualification', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=150), nullable=True))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('age')
        batch_op.drop_column('qualification')
        batch_op.drop_column('position')
        batch_op.drop_column('email')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
